name: CI

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: yarn install

    - name: Check code formatting
      run: yarn prettier-check

    - name: Check for Typescript compiler errors
      run: yarn tsc

    - name: Check for linting errors
      run: yarn lint

    - name: Run tests
      run: yarn run testCI

    - name: Build web app
      run: yarn build

    - name: Deploy web app to Firebase hosting
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: project-tracker-8ea42

